package main

// getStyles returns the demo page CSS, including suggested styling
// for every component in the components package
func getStyles() string {
	return `
* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #333;
    background: #f5f5f5;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.section {
    background: white;
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 2rem;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.section h2 {
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid #eee;
}

/* Navigation */
.nav {
    background: #2c3e50;
    padding: 1rem 2rem;
    display: flex;
    align-items: center;
    gap: 2rem;
}

.nav-brand {
    color: white;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
}

.nav-list {
    list-style: none;
    display: flex;
    gap: 1rem;
}

.nav-link {
    color: rgba(255,255,255,0.8);
    text-decoration: none;
    padding: 0.5rem 1rem;
    border-radius: 4px;
}

.nav-link:hover, .nav-item.active .nav-link {
    color: white;
    background: rgba(255,255,255,0.1);
}

/* Breadcrumb */
.breadcrumb-list {
    list-style: none;
    display: flex;
    flex-wrap: wrap;
    padding: 0.75rem 0;
}

.breadcrumb-item { display: flex; align-items: center; }
.breadcrumb-item a { color: #3498db; text-decoration: none; }
.breadcrumb-item a:hover { text-decoration: underline; }
.breadcrumb-current { color: #666; }
.breadcrumb-separator { color: #999; margin: 0 0.25rem; }

/* Alerts */
.alert {
    padding: 1rem;
    border-radius: 4px;
    margin-bottom: 1rem;
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

.alert-info { background: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; }
.alert-success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
.alert-warning { background: #fff3cd; color: #856404; border: 1px solid #ffeeba; }
.alert-error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }

.alert-close {
    margin-left: auto;
    background: none;
    border: none;
    font-size: 1.25rem;
    cursor: pointer;
    opacity: 0.5;
}

.alert-close:hover { opacity: 1; }

/* Badges */
.badge {
    display: inline-block;
    padding: 0.25em 0.6em;
    font-size: 0.78rem;
    font-weight: 600;
    border-radius: 4px;
    margin-right: 0.35rem;
}

.badge-pill { border-radius: 999px; }
.badge-neutral { background: #e9ecef; color: #495057; }
.badge-info { background: #d1ecf1; color: #0c5460; }
.badge-success { background: #d4edda; color: #155724; }
.badge-warning { background: #fff3cd; color: #856404; }
.badge-error { background: #f8d7da; color: #721c24; }

/* Buttons */
.btn-row { display: flex; gap: 0.5rem; flex-wrap: wrap; margin-top: 1rem; }

.btn {
    display: inline-block;
    padding: 0.625rem 1.25rem;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    text-decoration: none;
    text-align: center;
}

.btn-primary { background: #3498db; color: white; }
.btn-primary:hover { background: #2980b9; }
.btn-secondary { background: #e9ecef; color: #333; }
.btn-secondary:hover { background: #dde1e5; }
.btn-danger { background: #e74c3c; color: white; }
.btn-danger:hover { background: #c0392b; }
.btn-sm { padding: 0.375rem 0.75rem; font-size: 0.875rem; }
.btn-lg { padding: 0.75rem 1.5rem; font-size: 1.125rem; }
.btn:disabled, .btn-disabled { opacity: 0.5; cursor: not-allowed; }

/* Table */
.table-responsive { overflow-x: auto; }

.table {
    width: 100%;
    border-collapse: collapse;
    margin: 1rem 0;
}

.table caption {
    caption-side: top;
    text-align: left;
    color: #666;
    font-size: 0.875rem;
    padding-bottom: 0.5rem;
}

.table th, .table td {
    padding: 0.75rem;
    text-align: left;
}

.table th {
    background: #3498db;
    color: white;
    font-weight: 600;
}

.table tfoot td { font-weight: 600; background: #f1f3f5; }
.table-striped tbody tr:nth-child(even) { background: #f8f9fa; }
.table-hover tbody tr:hover { background: #eef6fc; }
.table-bordered th, .table-bordered td { border: 1px solid #dee2e6; }
.table .row-highlight { background: #fff9e6 !important; }
.table-empty { text-align: center; color: #999; padding: 2rem !important; }

/* Tabs (structural show/hide rules are generated by the component) */
.tab-label {
    display: inline-block;
    padding: 0.5rem 1.25rem;
    cursor: pointer;
    border: 1px solid transparent;
    border-bottom: none;
    border-radius: 6px 6px 0 0;
    color: #3498db;
}

.tabs > .tab-radio:checked + .tab-label {
    background: white;
    border-color: #dee2e6;
    color: #333;
    font-weight: 600;
}

.tab-panels {
    border-top: 1px solid #dee2e6;
    padding: 1rem 0.25rem;
}

/* Accordion */
.accordion-item {
    border: 1px solid #dee2e6;
    border-radius: 6px;
    margin-bottom: 0.5rem;
    background: #fff;
}

.accordion-title {
    cursor: pointer;
    padding: 0.75rem 1rem;
    font-weight: 600;
    list-style-position: inside;
}

.accordion-item[open] .accordion-title { border-bottom: 1px solid #eee; }
.accordion-body { padding: 0.75rem 1rem; color: #555; }

/* Modal (Popover API) */
.modal {
    border: none;
    border-radius: 8px;
    box-shadow: 0 10px 40px rgba(0,0,0,0.25);
    padding: 0;
    max-width: 480px;
    width: 90%;
}

.modal::backdrop { background: rgba(0,0,0,0.45); }

.modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid #eee;
}

.modal-title { font-size: 1.1rem; }

.modal-close {
    background: none;
    border: none;
    font-size: 1.5rem;
    line-height: 1;
    cursor: pointer;
    opacity: 0.5;
}

.modal-close:hover { opacity: 1; }
.modal-body { padding: 1.25rem; }

/* Dropdown */
.dropdown { position: relative; display: inline-block; }

.dropdown-toggle {
    cursor: pointer;
    list-style: none;
    padding: 0.5rem 1rem;
    border: 1px solid #dee2e6;
    border-radius: 4px;
    background: white;
    user-select: none;
}

.dropdown-toggle::-webkit-details-marker { display: none; }

.dropdown-menu {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    min-width: 180px;
    list-style: none;
    background: white;
    border: 1px solid #dee2e6;
    border-radius: 6px;
    box-shadow: 0 6px 20px rgba(0,0,0,0.12);
    padding: 0.35rem 0;
    z-index: 100;
}

.dropdown-link {
    display: block;
    padding: 0.5rem 1rem;
    color: #333;
    text-decoration: none;
}

.dropdown-link:hover { background: #f1f3f5; }

.dropdown-divider {
    border-top: 1px solid #eee;
    margin: 0.35rem 0;
}

/* Progress */
.progress {
    background: #e9ecef;
    border-radius: 999px;
    height: 1.1rem;
    overflow: hidden;
    margin-bottom: 0.75rem;
}

.progress-lg { height: 1.6rem; }

.progress-fill {
    background: #3498db;
    height: 100%;
    color: white;
    font-size: 0.72rem;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: width 0.3s ease;
}

/* Definition List */
.definition-list {
    display: grid;
    grid-template-columns: max-content 1fr;
    gap: 0.5rem 1.5rem;
}

.definition-term { font-weight: 600; color: #2c3e50; }
.definition-desc { color: #555; }

/* Pagination */
.pagination-list {
    list-style: none;
    display: flex;
    gap: 0.25rem;
}

.pagination-list li { display: flex; }

.pagination-link, .pagination-current {
    padding: 0.5rem 0.75rem;
    border: 1px solid #ddd;
    border-radius: 4px;
    text-decoration: none;
    color: #3498db;
}

.pagination-link:hover { background: #f0f0f0; }

.pagination-current {
    background: #3498db;
    color: white;
    border-color: #3498db;
}

/* Form */
.form-field { margin-bottom: 1.25rem; }

.form-label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
}

.required { color: #e74c3c; }

.form-input {
    width: 100%;
    padding: 0.625rem;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 1rem;
    background: white;
}

.form-input:focus {
    outline: none;
    border-color: #3498db;
    box-shadow: 0 0 0 3px rgba(52,152,219,0.1);
}

.has-error .form-input { border-color: #e74c3c; }

.form-error {
    display: block;
    color: #e74c3c;
    font-size: 0.875rem;
    margin-top: 0.25rem;
}

.form-help {
    display: block;
    color: #666;
    font-size: 0.875rem;
    margin-top: 0.25rem;
}

/* Checkboxes and radios */
.form-check { display: flex; align-items: center; gap: 0.5rem; }
.form-check .form-check-input { width: auto; }
.form-check-label { font-weight: 400; }

.radio-group { border: none; padding: 0; }
.radio-group legend { margin-bottom: 0.5rem; }
.radio-group .radio-option { margin-bottom: 0.35rem; }

.radio-group-inline { display: block; }
.radio-group-inline .radio-option {
    display: inline-flex;
    margin-right: 1.25rem;
}

.form-actions { margin-top: 1.5rem; }

/* Footer */
.footer {
    text-align: center;
    padding: 2rem;
    color: #666;
    background: white;
    margin-top: 2rem;
}
`
}
